module.exports = [
  { name: "Meta", url: "https://www.meta.com/careers" },
  { name: "Microsoft", url: "https://careers.microsoft.com" },
  { name: "Pinterest", url: "https://careers.pinterest.com" },
  { name: "Walmart", url: "https://careers.walmart.com" },
  { name: "Salesforce", url: "https://www.salesforce.com/company/careers/" },
  { name: "Baidu", url: "https://talent.baidu.com" },
  { name: "Wix", url: "https://www.wix.com/jobs" },
  { name: "Shopify", url: "https://www.shopify.com/careers" },
  { name: "Discord", url: "https://discord.com/jobs" },
  { name: "Uber Eats", url: "https://www.uber.com/careers" },
  { name: "SoundCloud", url: "https://jobs.soundcloud.com" },
  { name: "Tesla", url: "https://www.tesla.com/careers" },
  { name: "Bloomberg", url: "https://www.bloomberg.com/careers" },
  { name: "Vogue", url: "https://condenast-careers.com/" },
  { name: "NerdWallet", url: "https://www.nerdwallet.com/careers" },
  { name: "Dropbox", url: "https://jobs.dropbox.com" },
  { name: "Starbucks", url: "https://www.starbucks.com/careers" },
  { name: "New York Times", url: "https://www.nytco.com/careers/" },
  { name: "Words With Friends", url: "https://www.zynga.com/careers/" },
  { name: "Trello", url: "https://www.atlassian.com/company/careers" },
  { name: "Gibbon Platform", url: "https://www.gibbonedu.org" },
  { name: "Call of Duty Companion App", url: "https://careers.activision.com" },
  { name: "Artsy", url: "https://www.artsy.net/about/jobs" },
  { name: "Green Thumb", url: "https://www.gtigrows.com/careers" },
  { name: "Flatiron Health", url: "https://flatiron.com/careers/" },
  { name: "Dealpath", url: "https://www.dealpath.com/careers/" },
  { name: "HoneyBook", url: "https://www.honeybook.com/careers" },
  { name: "Chetu, Inc.", url: "https://www.chetu.com/careers" },
  { name: "Zearn", url: "https://www.zearn.org/about/careers" },
  { name: "Domino Data Lab", url: "https://www.dominodatalab.com/careers/" },
  { name: "DUST Identity", url: "https://www.dustidentity.com/careers" },
  { name: "Terakeet", url: "https://www.terakeet.com/careers/" },
  { name: "Netflix", url: "https://jobs.netflix.com" },
  { name: "Yahoo", url: "https://www.verizonmedia.com/careers" },
  { name: "CBS Sports", url: "https://www.cbsnews.com/careers/" },
  { name: "Nike", url: "https://jobs.nike.com" },
  { name: "Reddit", url: "https://www.redditinc.com/careers" },
  { name: "Amazon", url: "https://www.amazon.jobs" },
  { name: "Stripe", url: "https://stripe.com/jobs" },
  { name: "Airbnb", url: "https://careers.airbnb.com" },
  { name: "GitHub", url: "https://github.com/about/careers" },
  { name: "Twitter", url: "https://careers.twitter.com" },
  { name: "LinkedIn", url: "https://careers.linkedin.com" },
  { name: "Snapchat", url: "https://www.snap.com/en-US/jobs" },
  { name: "Square", url: "https://squareup.com/careers" },
  { name: "Slack", url: "https://slack.com/careers" },
  { name: "PayPal", url: "https://jobs.paypal-corp.com" },
  { name: "Instacart", url: "https://careers.instacart.com" },
  { name: "Postmates", url: "https://www.uber.com/us/en/careers/" },
  { name: "Flipkart", url: "https://www.flipkartcareers.com/" },
  { name: "Bumble", url: "https://bumble.com/careers" },
  { name: "Robinhood", url: "https://careers.robinhood.com" },
  { name: "ByteDance", url: "https://jobs.bytedance.com/en" },
  { name: "TikTok", url: "https://careers.tiktok.com" },
  { name: "Alaska Airlines", url: "https://careers.alaskaair.com" },
  { name: "Expensify", url: "https://we.are.expensify.com/hiring" },
  { name: "Coursera", url: "https://about.coursera.org/careers" },
  { name: "GoFundMe", url: "https://www.gofundme.com/careers" },
  { name: "Notion", url: "https://www.notion.so/careers" },
  { name: "Spotify", url: "https://www.spotifyjobs.com" },
  { name: "Peloton", url: "https://www.onepeloton.com/careers" },
  { name: "Doordash", url: "https://careers.doordash.com" },
  { name: "ServiceTitan", url: "https://www.servicetitan.com/careers" },
  { name: "Headspace", url: "https://www.headspace.com/work-with-us" },
  { name: "RingCentral", url: "https://www.ringcentral.com/careers.html" },,
  { name: "Samsara", url: "https://www.samsara.com/company/careers" },
  { name: "Verizon", url: "https://www.verizon.com/about/work" },
  { name: "Citymapper", url: "https://citymapper.com/jobs" },
  { name: "Roku", url: "https://www.roku.com/jobs" },
  { name: "Virgin Pulse", url: "https://www.virginpulse.com/company/careers/" },
  { name: "Nubank", url: "https://nubank.com.br/en/careers/" },
  { name: "Bolt", url: "https://bolt.eu/en/careers" },
  { name: "Via", url: "https://ridewithvia.com/careers/" },
  { name: "Turo", url: "https://turo.com/careers" },
  { name: "eToro", url: "https://www.etoro.com/about/careers" },
  { name: "Toast", url: "https://careers.toasttab.com" },
  { name: "TruGreen", url: "https://jobs.trugreen.com/" },
  { name: "Farmers Insurance", url: "https://www.farmers.com/careers/" },
  { name: "JustWorks", url: "https://www.justworks.com/careers" },
  { name: "Lyft", url: "https://www.lyft.com/careers" },
  { name: "Snappr", url: "https://www.snappr.com/careers" },
  { name: "Better.com", url: "https://better.com/careers" },
  { name: "Thumbtack", url: "https://www.thumbtack.com/careers/" },
  { name: "Mynd", url: "https://mynd.com/careers" },
  { name: "Zola", url: "https://www.zola.com/careers" },
  { name: "CarGurus", url: "https://www.cargurus.com/careers/" },
  { name: "Calendly", url: "https://calendly.com/careers" },
  { name: "GoodRx", url: "https://www.goodrx.com/careers" },
  { name: "Gem", url: "https://www.gem.com/careers" },
  { name: "Policygenius", url: "https://www.policygenius.com/careers/" },
  { name: "Warby Parker", url: "https://www.warbyparker.com/jobs" },
  { name: "OpenTable", url: "https://careers.opentable.com" },
  { name: "Carbon Health", url: "https://carbonhealth.com/careers" },
  { name: "Oura", url: "https://ouraring.com/careers" },
  { name: "Soothe", url: "https://www.soothe.com/careers" },
  { name: "Orchard", url: "https://orchard.com/careers" },
  { name: "HealthJoy", url: "https://healthjoy.com/careers" },
  { name: "Lucid Software", url: "https://www.golucid.co/careers" },
  { name: "Heap", url: "https://heap.io/careers" },
  { name: "Airtable", url: "https://airtable.com/careers" },
  { name: "Codecademy", url: "https://www.codecademy.com/about/careers" },
  { name: "Braze", url: "https://www.braze.com/careers" },
  { name: "Unity", url: "https://unity.com/careers" },
  { name: "Monzo", url: "https://monzo.com/careers" },
  { name: "GrubHub", url: "https://careers.grubhub.com" },
  { name: "Doctor on Demand", url: "https://www.doctorondemand.com/careers" },
  { name: "Apollo Health", url: "https://apollohealthco.com/careers" },
  { name: "Intercom", url: "https://www.intercom.com/careers" },
  { name: "Chime", url: "https://www.chime.com/careers" },
  { name: "Glovo", url: "https://jobs.glovoapp.com/en/" },
  { name: "Asana", url: "https://asana.com/jobs" },
  { name: "Envoy", url: "https://envoy.com/careers" },
  { name: "DocuSign", url: "https://www.docusign.com/company/careers" },
  { name: "Udemy", url: "https://about.udemy.com/careers" },
  { name: "Ritual", url: "https://ritual.com/careers" },
  { name: "Loom", url: "https://www.loom.com/careers" },
  { name: "ClickUp", url: "https://clickup.com/careers" },
  { name: "Monday.com", url: "https://monday.com/careers" },
  { name: "Pleo", url: "https://www.pleo.io/en/careers" },
  { name: "HelloFresh", url: "https://www.hellofresh.com/careers" },
  { name: "ParcelLab", url: "https://parcellab.com/careers" },
  { name: "Carvana", url: "https://www.carvana.com/careers" },
  { name: "GoodLeap", url: "https://careers.goodleap.com" },
  { name: "MasterClass", url: "https://www.masterclass.com/careers" },
  { name: "Tonkean", url: "https://www.tonkean.com/careers" },
  { name: "Outreach", url: "https://www.outreach.io/company/careers" },
  { name: "Hipcamp", url: "https://www.hipcamp.com/jobs" },
  { name: "Zapier", url: "https://zapier.com/jobs" },
  { name: "Aircall", url: "https://aircall.io/careers" },
  { name: "Webflow", url: "https://webflow.com/careers" },
  { name: "Segment", url: "https://segment.com/careers" },
  { name: "Miro", url: "https://miro.com/careers" },
  { name: "PlushCare", url: "https://www.plushcare.com/careers" },
  { name: "SimplyInsured", url: "https://www.simplyinsured.com/careers" },
  { name: "Finicity", url: "https://www.finicity.com/careers" },
  { name: "Handshake", url: "https://joinhandshake.com/careers/" },
  { name: "Freshworks", url: "https://www.freshworks.com/company/careers/" },
  { name: "Vroom", url: "https://www.vroom.com/careers" },
  { name: "Nextdoor", url: "https://about.nextdoor.com/careers" },
  { name: "Front", url: "https://frontapp.com/jobs" },
  { name: "Evolv AI", url: "https://www.evolv.ai/careers" },
  { name: "Iterable", url: "https://iterable.com/company/careers" },
  { name: "Betterment", url: "https://www.betterment.com/careers" },
  { name: "Fetch Rewards", url: "https://www.fetchrewards.com/careers" },
  { name: "Onfido", url: "https://onfido.com/careers" },
  { name: "ZipRecruiter", url: "https://www.ziprecruiter.com/careers" },
  { name: "KeepTruckin", url: "https://www.keeptruckin.com/careers" },
  { name: "Hopper", url: "https://www.hopper.com/careers" },
  { name: "Convoy", url: "https://convoy.com/careers" },
  { name: "BigCommerce", url: "https://www.bigcommerce.com/careers" },
  { name: "Scaleway", url: "https://www.scaleway.com/en/careers" },
  { name: "Blueground", url: "https://www.theblueground.com/careers" },
  { name: "Paxos", url: "https://www.paxos.com/careers" },
  { name: "Glance", url: "https://inmobi.com/careers" },
  { name: "Snapcommerce", url: "https://snapcommerce.com/careers" },
  { name: "Tipalti", url: "https://tipalti.com/careers" },
  { name: "Cram", url: "https://www.cram.com/careers" },
  { name: "TalentCards", url: "https://www.talentcards.com/careers" },
  { name: "PowerDMS", url: "https://www.powerdms.com/careers" },
  { name: "Lessonly", url: "https://www.lessonly.com/careers" },
  { name: "Qstream", url: "https://www.qstream.com/careers" },
  { name: "MyQuest", url: "https://www.myquest.com/careers" },
  { name: "LearnUpon", url: "https://www.learnupon.com/careers" },
  { name: "Tovuti LMS", url: "https://www.tovutitechnologies.com/careers" },
  { name: "Trainual", url: "https://www.trainual.com/careers" },
  { name: "Bridge LMS", url: "https://www.bridgeapp.com/careers" },
  { name: "Mindflash", url: "https://www.mindflash.com/careers" },
  { name: "BizLibrary", url: "https://www.bizlibrary.com/careers" },
  { name: "Axonify", url: "https://www.axonify.com/careers" },
  { name: "SAP Litmos", url: "https://www.litmos.com/careers" },
  { name: "Docebo", url: "https://www.docebo.com/careers" },
  { name: "SuccessFactors", url: "https://www.successfactors.com/careers" },
  { name: "Absorb LMS", url: "https://www.absorblms.com/careers" },
  { name: "Moodle", url: "https://moodle.com/careers" },
  { name: "Canvas LMS", url: "https://www.instructure.com/careers" },
  { name: "BrainCert", url: "https://www.braincert.com/careers" },
  { name: "Adobe Captivate", url: "https://www.adobe.com/careers" },
  { name: "Zoho ShowTime", url: "https://www.zoho.com/careers" },
  { name: "WizIQ", url: "https://wiziq.com/careers" },
  { name: "Schoology", url: "https://www.schoology.com/careers" },
  { name: "Podia", url: "https://www.podia.com/careers" },
  { name: "SkyPrep", url: "https://www.skyprep.com/careers" },
  { name: "LearnWorlds", url: "https://www.learnworlds.com/careers" },
  { name: "LearnDash", url: "https://www.learndash.com/careers" },
  { name: "Kajabi", url: "https://kajabi.com/careers" },
  { name: "Teachable", url: "https://teachable.com/careers" },
  { name: "Thinkific", url: "https://www.thinkific.com/careers" },
  { name: "TalentLMS", url: "https://www.talentlms.com/careers" },
  { name: "Run The World", url: "https://www.runtheworld.com/careers" },
  { name: "Accelevents", url: "https://www.accelevents.com/careers" },
  { name: "EventMobi", url: "https://www.eventmobi.com/careers" },
  { name: "SwagUp", url: "https://www.swagup.com/careers" },
  { name: "Haystack", url: "https://haystackteam.com/careers" },
  { name: "SpotMe", url: "https://www.spotme.com/careers" },
  { name: "Attendify", url: "https://www.attendify.com/careers" },
  { name: "Social Tables", url: "https://www.socialtables.com/careers" },
  { name: "Bizzabo", url: "https://www.bizzabo.com/careers" },
  { name: "Brushfire", url: "https://www.brushfire.com/careers" },
  { name: "Whova", url: "https://whova.com/careers" },
  { name: "Cvent", url: "https://www.cvent.com/careers" },
  { name: "Ticketmaster", url: "https://www.ticketmaster.com/careers" },
  { name: "Peatix", url: "https://peatix.com/careers" },
  { name: "Eventbrite", url: "https://www.eventbrite.com/careers" },
  { name: "Hopin", url: "https://hopin.com/careers" },
  { name: "Beekeeper", url: "https://www.beekeeper.io/careers" },
  { name: "Remo", url: "https://remo.co/careers" },
  { name: "BlueJeans", url: "https://www.bluejeans.com/careers" },
  { name: "GoToMeeting", url: "https://www.goto.com/careers" },
  { name: "Lifesize", url: "https://www.lifesize.com/careers" },
  { name: "Whereby", url: "https://whereby.com/careers" },
  { name: "Webex", url: "https://www.webex.com/careers" },
  { name: "Google Meet", url: "https://about.google/careers" },
  { name: "Grasshopper", url: "https://grasshopper.com/careers" },
  { name: "Vonage", url: "https://www.vonage.com/careers" },
  { name: "8x8", url: "https://www.8x8.com/careers" },
  { name: "RingCentral", url: "https://www.ringcentral.com/careers.html" },
  { name: "Twilio", url: "https://www.twilio.com/company/jobs" },
  { name: "Dialpad", url: "https://www.dialpad.com/careers" },
  { name: "Zoom", url: "https://zoom.us/careers" },
  { name: "Aha!", url: "https://www.aha.io/careers" },
  { name: "ClickUp", url: "https://clickup.com/careers" },
  { name: "Teamwork", url: "https://www.teamwork.com/careers" },
  { name: "Slack", url: "https://slack.com/careers" },
  { name: "Lucidchart", url: "https://www.lucidchart.com/careers" },
  { name: "Smartsheet", url: "https://www.smartsheet.com/careers" },
  { name: "Miro", url: "https://miro.com/careers" },
  { name: "Notion", url: "https://www.notion.so/careers" },
  { name: "Monday.com", url: "https://monday.com/careers" },
  { name: "Asana", url: "https://asana.com/jobs" },
  { name: "Hootsuite", url: "https://hootsuite.com/careers" },
  { name: "SEMrush", url: "https://www.semrush.com/careers" },
  { name: "Sprout Social", url: "https://sproutsocial.com/careers" },
  { name: "Vouch", url: "https://www.vouch.us/careers" },
  { name: "Upwork", url: "https://www.upwork.com/careers" },
  { name: "Qualtrics", url: "https://www.qualtrics.com/careers" },
  { name: "SurveyMonkey", url: "https://www.surveymonkey.com/careers" },
  { name: "Unbounce", url: "https://unbounce.com/careers" },
  { name: "Mailchimp", url: "https://mailchimp.com/careers" },
  { name: "HubSpot", url: "https://www.hubspot.com/careers" },
  { name: "Squarespace", url: "https://www.squarespace.com/careers" },
  { name: "Adobe", url: "https://www.adobe.com/careers" },
  { name: "Pinterest", url: "https://careers.pinterest.com" },
  { name: "Crello", url: "https://crello.com/careers" },
  { name: "Canva", url: "https://www.canva.com/careers" },
  { name: "Looker", url: "https://looker.com/careers" },
  { name: "Printify", url: "https://www.printify.com/careers" },
  { name: "Printful", url: "https://www.printful.com/careers" }
];
