const recruitingFirms = [
  { name: "TEKsystems", description: "Specializes in IT staffing and services, focusing on long-term partnerships and flexibility.", url: "https://www.teksystems.com" },
  { name: "Robert Half Technology", description: "Provides temporary, project-based, and full-time placements across technology fields.", url: "https://www.roberthalf.com" },
  { name: "CyberCoders", description: "Focuses on permanent tech placements with a proprietary matching platform for high retention rates.", url: "https://www.cybercoders.com" },
  { name: "Randstad Technologies", description: "Utilizes AI-driven tools for efficient tech staffing across various industries.", url: "https://www.randstadusa.com" },
  { name: "Mondo", description: "Specializes in rapid placements in digital marketing, tech, and creative sectors.", url: "https://www.mondo.com" },
  { name: "Apex Systems", description: "Covers tech, science, and engineering staffing, focusing on government and healthcare.", url: "https://www.apexsystems.com" },
  { name: "Insight Global", description: "Provides short- and long-term staffing solutions in tech and engineering fields.", url: "https://www.insightglobal.com" },
  { name: "Nexus IT Group", description: "Focuses on quick and high-quality placements in software development for various companies.", url: "https://www.nexusitgroup.com" },
  { name: "180 Engineering", description: "Specializes in executive and engineering roles with a relationship-based approach.", url: "https://www.180engineering.com" },
  { name: "Redfish Technology", description: "Offers tech staffing in SaaS, cloud, security, and related roles since 1996.", url: "https://www.redfishtech.com" },
  { name: "Toptal", description: "Global freelancing platform for elite software developers, designers, and managers.", url: "https://www.toptal.com" },
  { name: "Motion Recruitment", description: "Staffing firm for specialized roles in mobile, cybersecurity, UX, and data.", url: "https://www.motionrecruitment.com" },
  { name: "NerdRabbit", description: "AWS-certified recruiters for cloud, tech, and marketing positions.", url: "https://www.nerdrabbit.com" },
  { name: "Advantis Global", description: "Tech staffing for IT, data, gaming, cybersecurity, and creative sectors.", url: "https://www.advantisglobal.com" },
  { name: "Betts Recruiting", description: "Specializes in tech sales, marketing, and operations staffing.", url: "https://www.bettsrecruiting.com" },
  { name: "Riviera Partners", description: "Focuses on engineering, product, and design roles with data-driven matching.", url: "https://www.rivierapartners.com" },
  { name: "Diversant", description: "Large African-American-owned tech staffing firm, specializing in flexible hiring solutions.", url: "https://www.diversant.com" },
  { name: "Addison Group", description: "Offers specialized staffing in tech, finance, and HR fields.", url: "https://www.addisongroup.com" },
  { name: "Adecco", description: "Utilizes a vast database for matching tech and creative talent with companies.", url: "https://www.adeccousa.com" },
  { name: "Express Employment Professionals", description: "Offers IT staffing for various international locations.", url: "https://www.expresspros.com" },
  { name: "Hired", description: "Platform connecting tech professionals with actively hiring companies.", url: "https://www.hired.com" },
  { name: "Michael Page Technology", description: "Provides permanent and contract placements in tech roles.", url: "https://www.michaelpage.com" },
  { name: "Stafflink", description: "Tech recruitment firm with a hands-on approach to the hiring process.", url: "https://www.stafflink.ca" },
  { name: "Sparks Group", description: "Provides contract and full-time placements across multiple fields, including tech.", url: "https://www.sparksgroupinc.com" },
  { name: "Experis", description: "Specializes in IT staffing and consulting for project-based roles.", url: "https://www.experis.com" },
  { name: "Modis", description: "Combines IT and engineering staffing with consulting services.", url: "https://www.modis.com" },
  { name: "TriNet", description: "HR and payroll services with tech staffing for startups and small businesses.", url: "https://www.trinet.com" },
  { name: "Kelly Services", description: "Offers temp and contract-to-hire placements in various tech fields.", url: "https://www.kellyservices.com" },
  { name: "The Judge Group", description: "Provides IT staffing, consulting, and managed services for multiple sectors.", url: "https://www.judge.com" },
  { name: "Lucas Group", description: "Executive search firm specializing in tech and engineering roles.", url: "https://www.lucasgroup.com" },
  { name: "Allegis Group", description: "Provides comprehensive staffing and workforce management in tech.", url: "https://www.allegisgroup.com" },
  { name: "Fahrenheit IT", description: "IT staffing firm focusing on local talent and consulting services.", url: "https://www.fahrenheitit.com" },
  { name: "DISYS", description: "Offers IT staffing and managed services for mid- to large-scale companies.", url: "https://www.disys.com" },
  { name: "Hirewell", description: "Tech recruiting firm focusing on growth-stage companies and startups.", url: "https://www.hirewell.com" },
  // { name: "Onward Search", description: "Provides staffing for digital, creative, and technology roles.", url: "https://www.onwardsearch.com" },
  { name: "Procom", description: "IT staffing with a focus on project-based and consulting roles.", url: "https://www.procomservices.com" },
  { name: "Tech USA", description: "Offers full lifecycle staffing solutions in engineering and IT.", url: "https://www.techusa.net" },
  { name: "LaSalle Network", description: "Specializes in staffing for healthcare, finance, and technology.", url: "https://www.thelasallenetwork.com" },
  { name: "IntelliSource", description: "Provides outsourced staffing and tech recruitment solutions.", url: "https://www.intellisource.com" },
  { name: "Matrix Resources", description: "IT staffing and workforce solutions provider in the U.S.", url: "https://www.matrixres.com" },
  { name: "Cypress HCM", description: "Provides tech staffing solutions with a personalized approach.", url: "https://www.cypresshcm.com" },
  { name: "Mindlance", description: "IT staffing and consulting for Fortune 1000 clients.", url: "https://www.mindlance.com" },
  { name: "Revature", description: "Specializes in entry-level tech training and placement.", url: "https://www.revature.com" },
  { name: "WinterWyman", description: "Provides tech and finance staffing services.", url: "https://www.winterwyman.com" },
  { name: "Workbridge Associates", description: "Specializes in tech placements for startups and mid-sized companies.", url: "https://www.workbridgeassociates.com" },
  { name: "Beacon Hill Staffing Group", description: "Staffing for legal, tech, and healthcare sectors.", url: "https://www.beaconhillstaffing.com" },
  { name: "Vaco", description: "Offers finance, IT, and healthcare recruiting.", url: "https://www.vaco.com" },
  { name: "Career Movement", description: "Boutique firm specializing in tech talent placement.", url: "https://www.careermovement.com" },
  { name: "NextGen Global Resources", description: "Focuses on tech and telecom recruiting.", url: "https://www.nextgengr.com" },
  { name: "Global Technical Talent", description: "Specializes in tech recruiting and IT workforce solutions.", url: "https://www.gttit.com" },
  { name: "Green Key Resources", description: "Specializes in tech, finance, and pharma staffing.", url: "https://www.greenkeyllc.com" },
  // { name: "Paladin", description: "Specializes in staffing for marketing, digital, and creative sectors.", url: "https://www.paladinstaff.com" },
  { name: "Epitec", description: "Offers tech and engineering staffing, including project-based solutions.", url: "https://www.epitec.com" },
  { name: "ConsultNet", description: "Provides technical staffing with a focus on engineering and IT roles.", url: "https://www.consultnet.com" },
  { name: "OpenArc", description: "IT staffing for software development, data, and gaming industries.", url: "https://www.openarc.net" },
  { name: "Gables Search Group", description: "Specializes in executive and IT staffing solutions.", url: "https://www.gablessearch.com" },
  { name: "ASI System Integration", description: "IT staffing and consulting services for large organizations.", url: "https://www.asisystem.com" },
  { name: "PeopleLink Staffing Solutions", description: "Provides staffing solutions in tech, healthcare, and manufacturing.", url: "https://www.peoplelinkstaffing.com" },
  { name: "SmartIT", description: "Focused on high-quality placements in IT project management and software.", url: "https://www.smart-itstaffing.com" },
  { name: "Information Technology Partners", description: "IT staffing and managed services, specializing in government projects.", url: "https://www.itp.biz" },
  { name: "Emineo Group", description: "Specializes in IT staffing, focusing on project management and development.", url: "https://www.emineogroup.com" },
  { name: "Mainz Brady Group", description: "Technical staffing for software, design, and project management roles.", url: "https://www.mainzbradygroup.com" },
  { name: "Resolution Technologies", description: "Offers staffing for IT infrastructure and engineering roles.", url: "https://www.resolution-tech.com" },
  { name: "Paramount Software Solutions", description: "Focuses on IT consulting and staffing for government and commercial sectors.", url: "https://www.paramountsoft.net" },
  { name: "Anderson Frank", description: "Specialized staffing for NetSuite professionals in the tech sector.", url: "https://www.andersonfrank.com" },
  { name: "TEEMA Solutions Group", description: "Tech staffing for various industries with an emphasis on culture fit.", url: "https://www.teemagroup.com" },
  { name: "Brilliant", description: "Focuses on accounting, finance, and IT staffing.", url: "https://www.brilliantfs.com" },
  { name: "Bayside Solutions", description: "Staffing firm focused on tech, life sciences, and engineering.", url: "https://www.baysidesolutions.com" },
  { name: "Hays IT Staffing", description: "Global staffing firm providing tech and IT recruitment services.", url: "https://www.hays.com" },
  { name: "iPlace", description: "Provides offshore recruiting solutions, focusing on IT roles.", url: "https://www.iplaceusa.com" },
  { name: "SSI People", description: "IT staffing firm specializing in engineering and data science roles.", url: "https://www.ssipeople.com" },
  { name: "Data Inc.", description: "Provides IT staffing and consulting for data management and software.", url: "https://www.datainc.com" },
  { name: "Primus Software Corporation", description: "IT staffing with a focus on telecom and financial services.", url: "https://www.primussoft.com" },
  { name: "Dahl Consulting", description: "Staffing services specializing in IT, finance, and healthcare.", url: "https://www.dahlconsulting.com" },
  { name: "Netsource", description: "Tech staffing with a focus on project-based solutions and consultants.", url: "https://www.netsource.com" },
  { name: "True North", description: "Executive search and IT staffing with a client-focused approach.", url: "https://www.truenorthconsulting.com" },
  { name: "Roth Staffing", description: "Offers staffing in IT, legal, and finance, focusing on culture fit.", url: "https://www.rothstaffing.com" },
  { name: "SkillStorm", description: "Focuses on training and deploying tech talent for enterprise needs.", url: "https://www.skillstorm.com" },
  { name: "CTG", description: "Offers staffing for IT projects with a focus on healthcare IT.", url: "https://www.ctg.com" },
  { name: "Nesco Resource", description: "Provides tech, industrial, and administrative staffing.", url: "https://www.nescoresource.com" },
  { name: "Forrest Solutions", description: "Specializes in tech, administrative, and sales staffing.", url: "https://www.forrestsolutions.com" },
  { name: "AllSTEM Connections", description: "Diversity-focused staffing for STEM fields, including tech.", url: "https://www.allstemconnections.com" },
  { name: "ISGF", description: "Specializes in IT staffing with a focus on full-cycle hiring.", url: "https://www.isgf.com" },
  { name: "Xsell Resources", description: "IT staffing firm focused on software development and consulting roles.", url: "https://www.xsellresources.com" },
  { name: "eTeam", description: "Global IT staffing firm with a focus on enterprise solutions.", url: "https://www.eteaminc.com" },
  { name: "Compunnel", description: "Provides IT staffing and digital transformation services.", url: "https://www.compunnel.com" },
  { name: "Amerit Consulting", description: "Veteran-owned firm offering IT and engineering staffing.", url: "https://www.ameritconsulting.com" },
  { name: "Veredus", description: "IT staffing firm specializing in consulting and permanent placements.", url: "https://www.vereduscorp.com" },
  { name: "DT Professional Services", description: "IT staffing focused on engineering, aerospace, and defense sectors.", url: "https://www.dtprofessionals.com" },
  { name: "The Select Group", description: "Specializes in tech and engineering staffing with a consultative approach.", url: "https://www.selectgroup.com" },
  { name: "The BOSS Group", description: "Focuses on staffing for creative and tech fields.", url: "https://www.thebossgroup.com" },
  { name: "ATR International", description: "Offers staffing for IT, engineering, and scientific roles.", url: "https://www.atrinternational.com" },
  { name: "Alltech International", description: "Provides IT consulting and staffing for government clients.", url: "https://www.alltech.net" },
  { name: "GCR", description: "Focuses on tech staffing for government and commercial clients.", url: "https://www.gcrtemps.com" },
  { name: "Nectar Consulting", description: "Staffing firm focused on tech roles and career coaching.", url: "https://www.nectarconsulting.com" },
  { name: "NextDeavor", description: "Provides staffing for tech and HR roles with a personalized approach.", url: "https://www.nextdeavor.com" },
  { name: "JVT Advisors", description: "IT staffing firm specializing in project-based placements.", url: "https://www.jvtadvisors.com" },
  { name: "Next Step Systems", description: "Specializes in IT recruiting for development, support, and engineering.", url: "https://www.nextstepsystems.com" },
  { name: "BrainWorks", description: "Offers staffing in tech, marketing, and analytics.", url: "https://www.brainworksinc.com" },
  { name: "ASG Staffing", description: "Specializes in industrial, logistics, and tech staffing solutions.", url: "https://www.asgstaffing.com" },
  { name: "LevelUP HCS", description: "Focuses on engineering and IT staffing, with a solutions-based approach.", url: "https://www.leveluphcs.com" },
  { name: "Sedna Consulting", description: "IT staffing for various industries, focusing on client alignment.", url: "https://www.sednaglobal.com" },
  { name: "Career Strategies", description: "Provides tech and executive placements across multiple sectors.", url: "https://www.csi4jobs.com" },
  { name: "Vital Tech Solutions", description: "Specializes in healthcare IT staffing and managed services.", url: "https://www.vitaltechsolutions.com" },
  { name: "Eventus", description: "Offers IT staffing and business process outsourcing services.", url: "https://www.eventusg.com" },
  { name: "Digital Intelligence Systems", description: "Global IT staffing and consulting firm for various industries.", url: "https://www.distech.com" },
  { name: "Corestaff Services", description: "Specializes in tech, industrial, and administrative staffing.", url: "https://www.corestaff.com" },
  { name: "Business Centric Technology", description: "Provides tech staffing with an emphasis on industry-specific needs.", url: "https://www.bct-corp.com" },
  { name: "Infinity Consulting Solutions", description: "Provides staffing for IT, accounting, and corporate operations.", url: "https://www.infinity-cs.com" },
  { name: "System One", description: "Specializes in engineering, technology, and legal staffing.", url: "https://www.systemone.com" },
  { name: "EdgeLink", description: "IT staffing with a focus on software engineering and development.", url: "https://www.edgelink.com" },
  { name: "Alignstaffing", description: "Education and healthcare-focused staffing agency.", url: "https://www.alignstaffing.com" },
  { name: "Turning Point Staffing", description: "Provides executive and mid-level staffing services.", url: "https://www.turningpointsearch.net" },
  { name: "The Phoenix Group", description: "Tech-focused recruiting firm in the NYC area.", url: "https://www.thephoenixgrp.com" },
  { name: "BlueWave", description: "IT and tech recruiting firm for early and growth-stage companies.", url: "https://www.bluewave.net" },
  { name: "DIVERSANT", description: "Focuses on IT staffing for Fortune 500 companies.", url: "https://www.diversant.com" },
  { name: "Pride Global", description: "Delivers staffing in IT, finance, and professional sectors.", url: "https://www.prideglobal.com" },
  { name: "Signature Consultants", description: "Provides IT staffing and project-based consulting.", url: "https://www.sigconsult.com" },
  { name: "Creative Circle", description: "Specializes in creative, marketing, and digital staffing.", url: "https://www.creativecircle.com" },
  { name: "TEK Connexion", description: "IT staffing services for the healthcare and finance sectors.", url: "https://www.tekconnexion.com" },
  { name: "Anchor Staffing", description: "Administrative and light industrial staffing firm.", url: "https://www.anchorstaffing.com" },
  { name: "CORE Staffing Services", description: "Provides staffing in legal, finance, and creative fields.", url: "https://www.employcore.com" },
  { name: "Talent Navigation Experts", description: "Tech and finance staffing, focusing on talent alignment.", url: "https://www.talentnavigation.com" },
  { name: "TRC Staffing Services", description: "Full-service staffing firm for industrial, administrative, and tech roles.", url: "https://www.trcstaffing.com" }
];
